# fly.toml app configuration file generated for trying-astrodb on 2023-07-17T18:07:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trying-astrodb"
primary_region = "ord"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
